{
    "openapi": "3.0.0",
    "info": {
        "title": "Book-Comet",
        "description": "E-commerce api to sell books and ebooks.",
        "contact": {
            "email": "lucasdotcampos@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:5555/",
            "description": "host server"
        }
    ],
    "paths": {
        "/book/register": {
            "post": {
                "summary": "Route to register a book",
                "tags": ["Book"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Book"
                            },
                            "examples": {
                                "Book": {
                                    "value": {
                                        "name": "1984",
                                        "author": "George Martin",
                                        "publisher": "Status",
                                        "yearOfPublication": "01/01/01",
                                        "summary": "a book about modern art"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "409": {
                        "description": "Book is already registered"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Book"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/book/list": {
            "get": {
                "summary": "You'll get a list of all the registered books",
                "tags": ["Book"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Book"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/book/list/author/{author}": {
            "get": {
                "summary": "You'll get books by their author",
                "tags": ["Book"],
                "parameters": [
                    {
                        "name": "author",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Book"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/book/list/publisher/{publisher}": {
            "get": {
                "summary": "You'll get books by their publisher",
                "tags": ["Book"],
                "parameters": [
                    {
                        "name": "publisher",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Book"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/book/update/{bookId}": {
            "put": {
                "summary": "Route to update informations about a book",
                "tags": ["Book"],
                "parameters": [
                    {
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/book"
                            },
                            "examples": {
                                "Book": {
                                    "value": {
                                        "name": "1984",
                                        "author": "George Orwell",
                                        "publisher": "Secker and Warburg",
                                        "yearOfPublication": "06/08/1949",
                                        "summary": "1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of 'the Party', who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. 'Big Brother' controls every aspect of people's lives"
                                    }
                                }
                            }
                        }
                    }
                },

                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Book"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/book/delete/{bookId}": {
            "delete": {
                "summary": "You'll get books by their publisher",
                "tags": ["Book"],
                "parameters": [
                    {
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "ERROR",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Book"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/ebook/register": {
            "post": {
                "summary": "Route to register a ebook",
                "tags": ["Ebook"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Ebook"
                            },
                            "examples": {
                                "Book": {
                                    "value": {
                                        "name": "1984",
                                        "author": "George Martin",
                                        "publisher": "Status",
                                        "yearOfPublication": "01/01/01",
                                        "summary": "a book about modern art",
                                        "format": "pdf"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "409": {
                        "description": "Book is already registered"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Book"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/ebook/list": {
            "get": {
                "summary": "You'll get a list of all the registered ebooks",
                "tags": ["Ebook"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Ebook"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/ebook/list/author/{author}": {
            "get": {
                "summary": "You'll get ebooks by their author",
                "tags": ["Ebook"],
                "parameters": [
                    {
                        "name": "author",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Ebook"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/ebook/list/publisher/{publisher}": {
            "get": {
                "summary": "You'll get ebooks by their publisher",
                "tags": ["Ebook"],
                "parameters": [
                    {
                        "name": "publisher",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Ebook"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/ebook/update/{ebookId}": {
            "put": {
                "summary": "Route to update informations about a ebook",
                "tags": ["Ebook"],
                "parameters": [
                    {
                        "name": "ebookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/ebook"
                            },
                            "examples": {
                                "Ebook": {
                                    "value": {
                                        "name": "1984",
                                        "author": "George Orwell",
                                        "publisher": "Secker and Warburg",
                                        "yearOfPublication": "06/08/1949",
                                        "summary": "1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of 'the Party', who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. 'Big Brother' controls every aspect of people's lives",
                                        "format": "epub"
                                    }
                                }
                            }
                        }
                    }
                },

                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Ebook"
                                }
                            }
                        }
                    }
                }
            }
        },

        "/inventory/register": {
            "post": {
                "summary": "Route to register a book in the inventory",
                "tags": ["Inventory"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Inventory"
                            },
                            "examples": {
                                "Book": {
                                    "value": {
                                        "name": "1984",
                                        "author": "George Orwell",
                                        "quantity": 100
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Book is already registered"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Inventory"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/inventory/update/{bookId}": {
            "put": {
                "summary": "Route to update informations about a book on the inventory",
                "tags": ["Inventory"],
                "parameters": [
                    {
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Inventory"
                            },
                            "examples": {
                                "book": {
                                    "value": {
                                        "name": "1984",
                                        "author": "George Orwell",
                                        "quantity": 0
                                    }
                                }
                            }
                        }
                    }
                },

                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Inventory"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/inventory/delete/{bookId}": {
            "delete": {
                "summary": "You'll delete book from the inventory",
                "tags": ["Inventory"],
                "parameters": [
                    {
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "ERROR",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Inventory"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/inventory/list": {
            "get": {
                "summary": "You'll get a list of registered books",
                "tags": ["Inventory"],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Inventory"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Book": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "author": {
                        "type": "string"
                    },
                    "publisher": {
                        "type": "string"
                    },
                    "yearOfPublication": {
                        "type": "string"
                    },
                    "summary": {
                        "type": "string"
                    }
                }
            },
            "Ebook": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "author": {
                        "type": "string"
                    },
                    "publisher": {
                        "type": "string"
                    },
                    "yearOfPublication": {
                        "type": "string"
                    },
                    "summary": {
                        "type": "string"
                    },
                    "format": {
                        "type": "string"
                    }
                }
            },

            "Inventory": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "author": {
                        "type": "string"
                    },
                    "quantity": {
                        "type": "number"
                    }
                }
            }
        }
    }
}
